package com.raullopezpenalva.newsletter_service.modules.newsletter.domain.model;
    
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "subscribers")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Subscriber entity representing a newsletter subscriber")
public class Subscriber {

    @Id
    @GeneratedValue
    @NonNull
    private UUID id;

    @Email
    @NotBlank
    @Column(nullable = false, unique = true)
    @Size(min = 5, max = 254)
    private String email;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private SubscriptionStatus status;

    
    private boolean userCreated;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    
    private LocalDateTime verifiedAt;

    
    private LocalDateTime updatedAt;

    @Column(nullable = true, columnDefinition = "TEXT")
    @Size(max = 4000)
    private String adminNote;

    @Column(nullable = true)
    private String sourceIp;

    @Column(nullable = true, columnDefinition = "TEXT")
    @Size(max = 4000)
    private String userAgent;

    // Getters and Setters (can be generated by Lombok)

    public UUID getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public SubscriptionStatus getStatus() {
        return status;
    }

    public boolean isUserCreated() {
        return userCreated;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getVerifiedAt() {
        return verifiedAt;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setStatus(SubscriptionStatus status) {
        this.status = status;
    }

    public void setUserCreated(boolean userCreated) {
        this.userCreated = userCreated;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setVerifiedAt(LocalDateTime verifiedAt) {
        this.verifiedAt = verifiedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public void setAdminNote(String adminNote) {
        this.adminNote = adminNote;
    }
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public String getAdminNote() {
        return adminNote;
    }

    public String getSourceIp() {
        return sourceIp;
    }

    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }

    public String getUserAgent() {
        return userAgent;
    }

    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }
}