version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: newsletter_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: newsletter_db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newsletter_network
  
  Email-Service:
    image: maildev/maildev
    container_name: email_service
    ports:
      - "1080:1080"  # Web UI
    expose:
      - 1025      # SMTP
    networks:
      - newsletter_network

  testnewsletter-service:
    build: .
    container_name: testnewsletter_service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - Email-Service
    networks:
      - newsletter_network

volumes:
  postgres_data:

networks:
  newsletter_network:
    driver: bridge