@startuml component_diagram_newsletter_service

title Diagrama de Componentes - Newsletter Service

package "newsletter-service" {
  
  [NewsletterController] --> [NewsletterService]

  [NewsletterService] --> [TokenService]
  [NewsletterService] --> [SubscriberRepository]
  [NewsletterService] --> [EmailService]
  
  [TokenService] --> [VerificationTokenRepository]

}

[Frontend WebApp] --> [NewsletterController] : subscribe / verify and unsubscribe flow

[Email Sender Newsletter] --> [NewsletterController] : getUnsubscribeLink

[NewsletterController] ..> [OpenAPI Docs] : exposed via Swagger
[SubscriberRepository] --> [PostgreSQL DB]
[VerificationTokenRepository] --> [PostgreSQL DB]
[EmailService] --> [SMTP Server] : send confirmation email

@enduml
