@startuml subscribe_sequence_diagram
actor User

participant "Newsletter-FrontEnd" as Frontend
participant "NewsletterController" as Controller
participant "NewsletterService" as Service
participant "TokenService" as TokenService
participant "EmailService" as EmailService
participant "SubscriberRepository" as Repo
participant "VerificationTokenRepository" as TokenRepo

User -> Frontend : Summit subscription form (email, userCreated)
activate Frontend
Frontend -> Controller : POST /subscribe (email, userCreated)
deactivate Frontend

activate Controller
Controller -> Service : subscribe(email, userCreated)
activate Service

Service -> Repo : findByEmail(email)
activate Repo
Repo --> Service : return if email exists or not
deactivate Repo

alt Email already subscribed and active
    Service --> Controller : "Already subscribed"
    Controller --> Frontend : "Already subscribed"
    activate Frontend
    Frontend --> User : "Already subscribed"
    deactivate Frontend
else Email subscribed but PENDING
    Service -> TokenService : invalidateOldTokens(email)
    activate TokenService
    TokenService -> TokenRepo : findAll CONFIRMATION tokens by email and set used=true
    activate TokenRepo
    TokenRepo --> TokenService : return updated tokens
    deactivate TokenRepo
    TokenService --> Service : return
    deactivate TokenService
    Service -> TokenService : generateToken(CONFIRMATION)
    activate TokenService
    TokenService -> TokenRepo : save(token)
    activate TokenRepo
    TokenRepo --> TokenService : return saved token
    deactivate TokenRepo
    TokenService --> Service : return token
    deactivate TokenService
    Service -> EmailService : sendConfirmationEmail(email, token)
    Service --> Controller : "Confirmation email resent"
    Controller --> Frontend : "Subscription pending confirmation"
    activate Frontend
    Frontend --> User : "Subscription pending confirmation"
    deactivate Frontend
else New email
    alt Email associated to already created user
    Service -> Repo : save(new Subscriber(status = ACTIVE))
    Service --> Controller : "Active subscription"
    Controller --> Frontend : "Active subscription"
    activate Frontend
    Frontend --> User : "Active subscription"
    deactivate Frontend

    else Email not associated to a user
    Service -> Repo : save(new Subscriber(status = PENDING))
    Service -> TokenService : generateToken(CONFIRMATION)
    activate TokenService
    TokenService -> TokenRepo : save(token)
    activate TokenRepo
    TokenRepo --> TokenService : return saved token
    deactivate TokenRepo
    TokenService --> Service : return token
    deactivate TokenService
    Service -> EmailService : sendConfirmationEmail(email, token)
    Service --> Controller : "Subscription pending confirmation"
    Controller --> Frontend : "Subscription pending confirmation"
    activate Frontend
    Frontend --> User : "Subscription pending confirmation"
    deactivate Frontend
    end
end

deactivate Service
deactivate Controller

@enduml
