@startuml state_diagram_subscriber

title Lifecycle of a Subscriber

[*] --> PENDING : New manual subscription
[*] --> ACTIVE : Automatic subscription due to userCreated=true

PENDING --> ACTIVE : Confirmation via token (CONFIRMATION)
ACTIVE --> UNSUBSCRIBED : Unsubscription confirmation (UNSUBSCRIBE token)
UNSUBSCRIBED --> PENDING : New manual subscription (re-registration)

@enduml
