@startuml unsubscribeLink_generation_sequence_diagram
entity "NewsletterEmailSenderService" as EmailSenderService

participant "NewsletterController" as Controller
participant "NewsletterService" as Service
participant "TokenService" as TokenService
participant "SubscriberRepository" as Repo
participant "VerificationTokenRepository" as TokenRepo

actor Usuario

EmailSenderService -> Controller : GET Active Subscribers Unsubscribe Links
activate EmailSenderService
activate Controller
Controller -> Service : getAllActiveSubscribers()
activate Service
Service -> Repo : findAllByStatus(ACTIVE)
activate Repo
Repo --> Service : return List<Subscriber>
deactivate Repo
Service -> TokenService : generateUnsubscribeToken(subscriber)
activate TokenService
TokenService -> TokenRepo : save(UnsubscribeToken)
activate TokenRepo
TokenRepo --> TokenService : return saved UnsubscribeToken
deactivate TokenRepo
TokenService --> Service : return UnsubscribeToken
deactivate TokenService
Service --> Controller : return List<SubscriberWithUnsubscribeLink>
deactivate Service
Controller --> EmailSenderService : return List<SubscriberWithUnsubscribeLink>
deactivate Controller
deactivate EmailSenderService

@enduml