@startuml unsubscribe_sequence_diagram
actor Usuario

participant "NewsletterFrontend" as Frontend
participant "NewsletterController" as Controller
participant "NewsletterService" as Service
participant "TokenService" as TokenService
participant "SubscriberRepository" as Repo
participant "VerificationTokenRepository" as TokenRepo

Usuario -> Frontend : Use unsubscribe link
activate Usuario
Frontend -> Controller : GET /api/v1/newsletter/unsubscribe with token
activate Controller
Controller -> Service : Validates the token
activate Service
Service -> TokenService : findByToken(token) and check if not used, not expired and Unsubscribe type
activate TokenService
TokenService -> TokenRepo : findById(token)
activate TokenRepo
TokenRepo -> TokenService : return token
deactivate TokenRepo
TokenService --> Service : return token if valid or throw exception
deactivate TokenService
Service -> Controller : return status ok or forbidden
deactivate Service
alt Token is correct
  Controller -> Frontend : Response with 200 and email and new token
  activate Frontend
  Frontend -> Usuario : returns landing page with unsubscribe button
  deactivate Frontend
else Token not correct
  Controller -> Frontend : Response with forbidden
  activate Frontend
  Frontend -> Usuario : returns "Error" page
  deactivate Frontend
end
deactivate Controller

Usuario -> Frontend : User clicks the unsubscribe button
deactivate Usuario
activate Frontend
Frontend -> Controller : POST /api/v1/newsletter/confirm-unsubscription with token
deactivate Frontend
activate Controller 
Controller -> Service : Checks if the token is valid
activate Service
Service -> TokenService : findByToken(token) and check if not used, not expired and Unsubscribe type
activate TokenService
TokenService -> TokenRepo : findById(token)
activate TokenRepo
TokenRepo -> TokenService : return token
deactivate TokenRepo
TokenService --> Service : return token if valid or throw exception
deactivate TokenService

alt Token is correct
  Service -> Repo : change subscribe status to: UNSUBSCRIBE
  activate Repo
  Repo -> Service : return status
  deactivate Repo
  Service -> TokenService : invalidate the token (set used=true)
  activate TokenService
  TokenService -> TokenRepo : findById(token), set used=true and save
  activate TokenRepo
  TokenRepo --> TokenService : return updated token
  deactivate TokenRepo
  TokenService --> Service : return
  deactivate TokenService
  Service -> Controller : return status ok
  Controller -> Frontend : return status ok
  activate Frontend
  Frontend -> Usuario : return UNSUBSCRIBED message
  deactivate Frontend
else Token not correct
  Service -> Controller : return forbidden
  Controller -> Frontend : return forbidden
  activate Frontend
  Frontend -> Usuario : return "Error"
  deactivate Frontend
end

deactivate Service
deactivate Controller

@enduml
